// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webapia.Infrastructure.Data;

#nullable disable

namespace Webapia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831062046_AddImgUriRequired")]
    partial class AddImgUriRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Webapia.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("CreationTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("DATEDIFF(SECOND, '1970-01-01', SYSUTCDATETIME())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreationTimestamp");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a04c51-6d80-732b-a63a-425edc702774"),
                            CreationTimestamp = 1750000000,
                            Description = "27-inch 4K Display",
                            ImgUri = "https://img.alza.cz/m1.jpg",
                            Name = "Monitor",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-7168-7a2f-801d-56bcc4917746"),
                            CreationTimestamp = 1750000010,
                            Description = "Mechanical Keyboard",
                            ImgUri = "https://img.alza.cz/k1.jpg",
                            Name = "Keyboard",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-7550-7e53-afc7-a1c969e6176c"),
                            CreationTimestamp = 1750000020,
                            Description = "Wireless RGB Gaming Mouse",
                            ImgUri = "https://img.alza.cz/mouse1.jpg",
                            Name = "Gaming Mouse",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-7938-7b3b-9494-b2dfb5f11928"),
                            CreationTimestamp = 1750000030,
                            Description = "15-inch Performance Laptop",
                            ImgUri = "https://img.alza.cz/laptop1.jpg",
                            Name = "Laptop",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-7d20-7910-bb53-ca101a408cec"),
                            CreationTimestamp = 1750000040,
                            Description = "Wireless Noise Cancelling Headphones",
                            ImgUri = "https://img.alza.cz/headphones1.jpg",
                            Name = "Headphones",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-8108-76b8-b0b7-bfc4e5259d1d"),
                            CreationTimestamp = 1750000050,
                            Description = "Full HD USB Webcam",
                            ImgUri = "https://img.alza.cz/webcam1.jpg",
                            Name = "Webcam",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-84f0-7822-b7a7-5d3bbb201c28"),
                            CreationTimestamp = 1750000060,
                            Description = "7-in-1 USB-C Hub",
                            ImgUri = "https://img.alza.cz/hub1.jpg",
                            Name = "USB-C Hub",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-88d8-7634-b067-d1e0935b1005"),
                            CreationTimestamp = 1750000070,
                            Description = "1TB Portable SSD",
                            ImgUri = "https://img.alza.cz/ssd1.jpg",
                            Name = "External SSD",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-8cc0-7d77-8198-ec1cd446c538"),
                            CreationTimestamp = 1750000080,
                            Description = "Ergonomic Gaming Chair",
                            ImgUri = "https://img.alza.cz/chair1.jpg",
                            Name = "Gaming Chair",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-90a8-7b30-b95b-1948e4692bcb"),
                            CreationTimestamp = 1750000090,
                            Description = "LED Desk Lamp",
                            ImgUri = "https://img.alza.cz/lamp1.jpg",
                            Name = "Desk Lamp",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-9490-757c-953c-ad77c495bc14"),
                            CreationTimestamp = 1750000100,
                            Description = "128GB 5G Smartphone",
                            ImgUri = "https://img.alza.cz/phone1.jpg",
                            Name = "Smartphone",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-9878-71bc-9148-22ad0dc5df84"),
                            CreationTimestamp = 1750000110,
                            Description = "11-inch Tablet",
                            ImgUri = "https://img.alza.cz/tablet1.jpg",
                            Name = "Tablet",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-9c60-7e4d-ac92-d1a700cedc55"),
                            CreationTimestamp = 1750000120,
                            Description = "Fitness and Health Tracking",
                            ImgUri = "https://img.alza.cz/watch1.jpg",
                            Name = "Smart Watch",
                            Price = 229.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-a048-7f61-8b5a-d4ab0b923845"),
                            CreationTimestamp = 1750000130,
                            Description = "Portable Bluetooth Speaker",
                            ImgUri = "https://img.alza.cz/speaker1.jpg",
                            Name = "Bluetooth Speaker",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-a430-7f0f-b622-c2be8e9947e9"),
                            CreationTimestamp = 1750000140,
                            Description = "USB Condenser Microphone",
                            ImgUri = "https://img.alza.cz/microphone1.jpg",
                            Name = "Microphone",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-a818-7a75-8c77-8f7d76aafcda"),
                            CreationTimestamp = 1750000150,
                            Description = "High Performance Graphics Card",
                            ImgUri = "https://img.alza.cz/gpu1.jpg",
                            Name = "Graphics Card",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-ac00-7f69-b711-a64c0c7638b1"),
                            CreationTimestamp = 1750000160,
                            Description = "8-Core Desktop Processor",
                            ImgUri = "https://img.alza.cz/cpu1.jpg",
                            Name = "Processor",
                            Price = 349.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-afe8-7451-baa4-d7240366440d"),
                            CreationTimestamp = 1750000170,
                            Description = "32GB DDR5 Memory Kit",
                            ImgUri = "https://img.alza.cz/ram1.jpg",
                            Name = "RAM",
                            Price = 159.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-b3d0-7ec4-8c9c-7ae4b141ae6c"),
                            CreationTimestamp = 1750000180,
                            Description = "ATX Gaming Motherboard",
                            ImgUri = "https://img.alza.cz/motherboard1.jpg",
                            Name = "Motherboard",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-b7b8-70c7-ace9-1781ae65ec84"),
                            CreationTimestamp = 1750000190,
                            Description = "750W Modular Power Supply",
                            ImgUri = "https://img.alza.cz/psu1.jpg",
                            Name = "Power Supply",
                            Price = 109.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-bba0-7fc4-b146-9ac145fab374"),
                            CreationTimestamp = 1750000200,
                            Description = "Tempered Glass ATX Case",
                            ImgUri = "https://img.alza.cz/case1.jpg",
                            Name = "PC Case",
                            Price = 94.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-bf88-7671-b161-d56ed2220741"),
                            CreationTimestamp = 1750000210,
                            Description = "Wi-Fi 6 Router",
                            ImgUri = "https://img.alza.cz/router1.jpg",
                            Name = "Router",
                            Price = 139.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-c370-708e-9be1-e7922d4e09c1"),
                            CreationTimestamp = 1750000220,
                            Description = "Wireless Color Printer",
                            ImgUri = "https://img.alza.cz/printer1.jpg",
                            Name = "Printer",
                            Price = 189.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-c758-7c36-b501-267d1c97ba9b"),
                            CreationTimestamp = 1750000230,
                            Description = "Full HD Home Projector",
                            ImgUri = "https://img.alza.cz/projector1.jpg",
                            Name = "Projector",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-cb40-7338-839e-307fab222384"),
                            CreationTimestamp = 1750000240,
                            Description = "Virtual Reality Headset",
                            ImgUri = "https://img.alza.cz/vr1.jpg",
                            Name = "VR Headset",
                            Price = 449.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-cf28-7889-ad48-b74da2898f9f"),
                            CreationTimestamp = 1750000250,
                            Description = "Wireless Game Controller",
                            ImgUri = "https://img.alza.cz/controller1.jpg",
                            Name = "Game Controller",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-d310-713e-bd2f-6951020f5515"),
                            CreationTimestamp = 1750000260,
                            Description = "Programmable Mechanical Keypad",
                            ImgUri = "https://img.alza.cz/keypad1.jpg",
                            Name = "Mechanical Keypad",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-d6f8-7a30-85a3-692e8858e7ff"),
                            CreationTimestamp = 1750000270,
                            Description = "Adjustable Aluminum Laptop Stand",
                            ImgUri = "https://img.alza.cz/stand1.jpg",
                            Name = "Laptop Stand",
                            Price = 34.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-dae0-7411-9749-67c73d2cec66"),
                            CreationTimestamp = 1750000280,
                            Description = "Fast Wireless Charging Pad",
                            ImgUri = "https://img.alza.cz/charger1.jpg",
                            Name = "Wireless Charger",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = new Guid("01a04c51-dec8-77da-92fe-f30057578d28"),
                            CreationTimestamp = 1750000290,
                            Description = "128GB USB 3.2 Flash Drive",
                            ImgUri = "https://img.alza.cz/usb1.jpg",
                            Name = "USB Flash Drive",
                            Price = 19.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
